create table if not exists public.admin_users (id uuid primary key references auth.users(id) on delete cascade, created_at timestamptz not null default now());
create table if not exists public.content (id bigint generated by default as identity primary key,title text not null,type text not null check (type in ('أسئلة','ملازم','كتب','مراجعات')),stage text not null,subject text,price integer not null default 0 check (price >= 0),file_path text,created_at timestamptz not null default now());
alter table public.content add column if not exists price integer not null default 0;
do $$ begin
  if not exists (select 1 from pg_constraint where conname='content_price_nonnegative') then
    alter table public.content add constraint content_price_nonnegative check (price >= 0);
  end if;
end $$;
alter table public.admin_users enable row level security; alter table public.content enable row level security;
create policy "admins can read own admin row" on public.admin_users for select to authenticated using (id=auth.uid());
create policy "public can read content" on public.content for select to anon, authenticated using (true);
create policy "admins can insert content" on public.content for insert to authenticated with check (exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins can update content" on public.content for update to authenticated using (exists(select 1 from public.admin_users a where a.id=auth.uid())) with check (exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins can delete content" on public.content for delete to authenticated using (exists(select 1 from public.admin_users a where a.id=auth.uid()));
insert into storage.buckets (id,name,public) values ('library-files','library-files',true) on conflict (id) do nothing;
create policy "public can read library files" on storage.objects for select to anon, authenticated using (bucket_id='library-files');
create policy "admins can upload library files" on storage.objects for insert to authenticated with check (bucket_id='library-files' and exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins can update library files" on storage.objects for update to authenticated using (bucket_id='library-files' and exists(select 1 from public.admin_users a where a.id=auth.uid())) with check (bucket_id='library-files' and exists(select 1 from public.admin_users a where a.id=auth.uid()));
create policy "admins can delete library files" on storage.objects for delete to authenticated using (bucket_id='library-files' and exists(select 1 from public.admin_users a where a.id=auth.uid()));


-- Add academic branch for preparatory stage
alter table public.content add column if not exists branch text default '';
